{"name": "Email -- @1.1 ", "status": "failed", "statusDetails": {"message": "AssertionError: FAILED SUB-STEP: Then I am on cloudpayments page\nSubstep info: Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 49, in init_screen\n    context.current_page = page_class(context.driver)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 12, in __init__\n    self._verify_page()\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/cloudpaymetns_page.py\", line 26, in _verify_page\n    self.on_this_page('iframe')\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 19, in on_this_page\n    self.get_element(element_name)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 49, in get_element\n    return WebDriverWait(self.driver, timeout).until(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: Unable to locate element: \"iframe\"\n\n\nTraceback (of failed substep):\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 49, in init_screen\n    context.current_page = page_class(context.driver)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 12, in __init__\n    self._verify_page()\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/cloudpaymetns_page.py\", line 26, in _verify_page\n    self.on_this_page('iframe')\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 19, in on_this_page\n    self.get_element(element_name)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 49, in get_element\n    return WebDriverWait(self.driver, timeout).until(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_steps.py\", line 30, in step_impl\n    context.execute_steps('''\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n"}, "steps": [{"name": "Given clear time", "status": "passed", "start": 1608635291322, "stop": 1608635291323}, {"name": "When open f.gum24.online page", "status": "passed", "start": 1608635291324, "stop": 1608635296716}, {"name": "When clear time", "status": "passed", "start": 1608635296716, "stop": 1608635296716}, {"name": "When go to confirmation page", "status": "passed", "start": 1608635296717, "stop": 1608635483255}, {"name": "When calculate time for 'confirmation'", "status": "passed", "start": 1608635483255, "stop": 1608635483544}, {"name": "When go to cloudpayments page", "status": "failed", "statusDetails": {"message": "AssertionError: FAILED SUB-STEP: Then I am on cloudpayments page\nSubstep info: Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 49, in init_screen\n    context.current_page = page_class(context.driver)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 12, in __init__\n    self._verify_page()\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/cloudpaymetns_page.py\", line 26, in _verify_page\n    self.on_this_page('iframe')\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 19, in on_this_page\n    self.get_element(element_name)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 49, in get_element\n    return WebDriverWait(self.driver, timeout).until(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: Unable to locate element: \"iframe\"\n\n\nTraceback (of failed substep):\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 49, in init_screen\n    context.current_page = page_class(context.driver)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 12, in __init__\n    self._verify_page()\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/cloudpaymetns_page.py\", line 26, in _verify_page\n    self.on_this_page('iframe')\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 19, in on_this_page\n    self.get_element(element_name)\n  File \"/Users/kardash/Developer/fitness-automation/features/pages/base_page.py\", line 49, in get_element\n    return WebDriverWait(self.driver, timeout).until(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_steps.py\", line 30, in step_impl\n    context.execute_steps('''\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/behave/runner.py\", line 404, in execute_steps\n    assert False, message\n"}, "attachments": [{"name": "bug.png", "source": "f33987e6-11c4-441a-b676-55bbd353563c-attachment.png", "type": "image/png"}, {"name": "bug.png", "source": "a6fd9fe6-592b-4a6d-94b8-7ac82b1f11ca-attachment.png", "type": "image/png"}], "start": 1608635483545, "stop": 1608635490963}, {"name": "When enter fake card details", "status": "skipped", "start": 1608635490964, "stop": 1608635490964}, {"name": "Then I see cancel button element", "status": "skipped", "start": 1608635490964, "stop": 1608635490964}, {"name": "When calculate time for 'cloudpayments'", "status": "skipped", "start": 1608635490964, "stop": 1608635490964}], "parameters": [{"name": "page_name", "value": "f.gum24.online"}, {"name": "card", "value": "fake card"}, {"name": "type", "value": "cancel button"}], "start": 1608635291321, "stop": 1608635490964, "uuid": "28023cf3-a1f5-4905-8827-3760854c3c38", "historyId": "055759470ca507e62b8429e2c3fe0615", "fullName": "features/tests/2/cloudpayments10.feature:Email", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "validation"}, {"name": "feature", "value": "fitness-online.ru.com"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}